#!/bin/bash

set -x

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
cd "$SCRIPT_DIR/.."

uv run --dev ruff format --exclude dev_ui --exclude tests ./
uv run --dev dotenv-linter ./.env.example
uv run --dev ruff check --fix --exclude dev_ui --exclude tests ./
